### ISSUE TITLE
clarify wamt help and fix the typo ...

### ISSUE THREAD

**Issue by dhvines** [ibm-cloud-architecture/refarch-jee#11]
WAMT also has help and I believe that the rule help may in fact be the same in both.

There is also a type in the text "coming" => coming

> However, the Migration Toolkit for Application Binaries Analyze report has the advantage of comming with an explanation of the rule being applied so that the user can better understand the reason why a warning or error has been reported:

**Comment by jesusmah** [comment]
Added information about WAMT help in #13
