### ISSUE TITLE
websphere customization toolbox

### ISSUE THREAD

**Issue by dhvines** [ibm-cloud-architecture/refarch-jee#14]
> This procedure can be followed only if the migration is between different versions of WebSphere.

You may also want to mention that waspreupgrade and waspostupgrade can be used for more complex nd migrations ... I'm not certain, but the websphere customization toolkit may be limited to base; not nd. here's a link to the more general set of command line tools for the cloud migration strategy for nd.

See slides 4-8 and 12: https://ibm.box.com/s/4242qf5uw1iucbr8h5pdb16oijgn8ke3

You may also want to mention that the above tools are best suited for lift and shift scenarios where there is also a like for like migration of the cells. That is they are great where the target cell has the same number of node agents, the same number of clusters, the same number of cluster members, etc. Those tools do not work well if there is some consolidation or other re-architecture of their topologies. 

When there is refactoring of the topologies then that is when you may want to use the eclipse based wcmt. See slides 8-10 in https://ibm.box.com/s/4242qf5uw1iucbr8h5pdb16oijgn8ke3

**Comment by Hemankita** [comment]
Added the waspreupgrade and waspostupgrade migrations. Added the content too.
