### ISSUE TITLE
Config Migration

### ISSUE THREAD

**Issue by dhvines** [ibm-cloud-architecture/refarch-jee#15]
> WebSphere Customization Toolbox

I would change this name of the above to **Migration Wizard** and add this hyperlink **https://www.ibm.com/support/knowledgecenter/en/SSAW57_9.0.0/com.ibm.websphere.migration.nd.doc/ae/tmig_profiles_gui.html**

I would also change the example from using the WebSphere Customization Toolkit to using the recommended tooling as described in the above link

AND

~Eclipse-based **application** migration tool

The above name and hyperlink is incorrect. 

The name should be Eclipse based **configuration** migration tool

The hyperlink should be: **https://developer.ibm.com/wasdev/downloads/#asset/tools-WebSphere_Configuration_Migration_Tool**

**Comment by Hemankita** [comment]
Changed the names and added the hyperlinks. Also included the command line example.
