### ISSUE TITLE
Traditional WebSphere Applications

### ISSUE THREAD

**Issue by dhvines** [ibm-cloud-architecture/refarch-jee#16]
Change this section heading from this

> Traditional WebSphere Applications

to this

> Traditional WebSphere (Profile Migration)

AND 

Make this a section heading

> Third Party Application Servers / Traditional WebSphere Application Server

AND then change the name of that section heading to:

> Traditional WebSphere (Resource Migration

Note: I do not think you need to mention 3rd party app server migrations in the above section heading simply because the target audience is WAS V2V upgrade; they are not 3rd party app server migrations. That said, if you wanted to mention liberty migrations or 3rd party app server migrations then you can add notes in the text; but its not needed in the section heading

**Comment by Hemankita** [comment]
Modified the names.
