### ISSUE TITLE
Step 5.4: Redundant path specified for OpenVPN Config files (Windows Users)

### ISSUE THREAD

**Issue by TyMcCarthy** [ibm-cloud-architecture/refarch-jee#20]
Redundant Path Specified for OpenVPN for Windows Config Files:

1.) In Step 5.4, the user is directed to download the OpenVPN configuration files. This "openVPNConfig.zip" file, that is downloaded from the Bluemix WASaaS service dashboard by selecting the "Download VPN Configuration" button, has within itself an "openvpn" subdirectory where the .ovp, key and certificate files are located.

2.) The correct directory path (using the default suggested install path for the application binary, using the OpenVPN installer executable for Windows), where the files above MUST be located, is 

C:\Program Files\OpenVPN\config

3.) The instructions found at

 https://console.bluemix.net/docs/services/ApplicationServeronCloud/systemAccess.html#setup_openvpn 

(which were copied and pasted into the text of the this tutorial, and also linked from this page), tell the user to extract these files to C:\Program Files\OpenVPN\Config

4.) Therefore, by extracting the files as specified, they will extract to 

C:\Program Files\OpenVPN\Config\openvpn\ 

instead of  

C:\Program Files\OpenVPN\Config

which is required, according to both readme.txt files. 

After extracting the files from the "openVPNConfig.zip" to the directory noted in the instructions, I had to copy the .ovp, key and certificate files up a level in my directory, then delete the redundant "openvpn" subdirectory.

**Comment by Hemankita** [comment]
Fixed with the re-write suggested.
