### ISSUE TITLE
Step 5.4: Suggested Re-Write

### ISSUE THREAD

**Issue by TyMcCarthy** [ibm-cloud-architecture/refarch-jee#21]
Currently, these are the instructions in Step 5.4 of the end-to-end tutorial for setting up OpenVPN. My suggested re-write is **inline** below the original text:

_Original:_

"4. Once done, you can access the Admin console using the Open the Admin Console option. In order to access the Admin console, install the VPN as instructed.

    Windows 64-Bit (OpenVPN)
    Windows 32-Bit (OpenVPN)
    Linux (OpenVPN)
    Mac (Tunnelblick)

Download, extract, and install the VPN configuration files by clicking the Download button.

VPN - Windows Configuration

    From the openVPN Windows download link, download openvpn-install-2.3.4-I001-x86_64.exe for 64-bit, or openvpn-install-2.3.4-I001-i686.exe for 32-bit.

    Ensure you Run as a Windows Administrator and openVPN is installed.

    Download the VPN configuration files from the OpenVPN download link of the WebSphere Application Server in Bluemix instance in the service dashboard. Extract all four files in the compressed file to the {OpenVPN home}\config directory.

C:\Program Files\OpenVPN\Config

    Start the openVPN client program "OpenVPN GUI". Ensure that you select Run as a Windows Administrator to start the program. If you do not, you might not be able to connect."

_Replace with:_

**4. Now you will access the WASaaS Admin Console to reconfigure your WAS cloud server. But first, you need to install and configure a VPN connection (if you have not already done so as a prerequisite):

A. Install the VPN Client

For Windows users, use the links provided on your WASaaS dashboard to download the installation executables for the latest versions of OpenVPN. Once downloaded, these files can be opened in that location. Follow the installation instructions. Install the VPN client using the following directory:

C:\Program Files\OpenVPN

For Linux users, use the link provided on your WASaaS dashboard and download the application binary for your version of Linux to install OpenVPN.

For Mac users, use the link provided on your WASaaS dashboard and follow the instructions to download and install OpenVPN.

Note: no links provided in this section. Users will use the links provided on their Bluemix WASaaS dashboard.

B. Download and Extract the VPN Config Files

For Windows users, download the VPN configuration archive file using the "Download VPN Configuration" button on your WASaaS dashboard. From the download location, extract the files to the following **required** location:

C:\Program Files\OpenVPN\Config

For Linux and Mac users, download the VPN configuration archive file using the "Download VPN Configuration" button on your WASaaS dashboard. From the download location, extract the files to the following location:

{OpenVPN home}\config

C. Establish Your VPN Connection

For Windows users:

1.) Right-click on the OpenVPN GUI icon on your desktop, select "Run as administrator"
2.) Right-click on the OpenVPN GUI icon in your Windows system tray, select "Connect"

Your VPN connection should now be established.

For Linux and Mac users:

{Can someone with a Mac or Linux OS please complete this section?}

D. You should now be able to access the WASaaS Admin Console by selecting "Open the Admin Console" on your WASaaS dashboard.**

_Why the changes?_

1.) The original text of the tutorial contains the same links as provided on the WASaaS dashboard, however they are static and the WASaaS dashboard may be updated. Also, there are multiple overlapping and inconsistent links provided that confuse the setup process. Seems best to just use the links provided on the WASaaS dashboard.

2.) The instructions linked here:

https://console.bluemix.net/docs/services/ApplicationServeronCloud/systemAccess.html#setup_openvpn

are the same instructions copied and pasted into the tutorial. They are not clear, outdated and/or are incorrect. Here are corrections (Windows setup):

#1 - some of the OpenVPN download links reference v11 and some reference v4 of this client app. The WASaaS dashboard has the latest link.

#3 - see previous git issue when downloading and extracting VPN config files 

#4 - once the OpenGUI VPN client is started, the user must then right-click on the OpenVPN icon in the Windows system tray and choose "Connect"

All of these changes should be corrected with the above proposed re-write.

**Comment by Hemankita** [comment]
Updated the tutorial with the re-write. Also added the steps for MAC and Linux users.
