### ISSUE TITLE
Step 2: Heading consistency, better flow, and minor edits

### ISSUE THREAD

**Issue by TyMcCarthy** [ibm-cloud-architecture/refarch-jee#22]
Suggest the following edits to headings to improve consistency and provide clarity and also to enable the user to determine where they are within the larger migration plan; i.e., 

Phase 1: Plan (Strategy, Discovery), Phase 2: Assess (Evaluate, Inventory, Analyze), and Phase 3: Migrate (Dev, Code, Config) 

1.)

_Replace_

Step 2.1 Use the Migration Toolkit for Application Binaries to evaluate the applications

_With_

Step 2.1 Assess CustomerOrderServicesApp's readiness for migration

_Reason_

Step 2.1.1 says the same thing, and that is where we should say that, because Assessment (Phase 2) includes sub-phases of Evaluation, Inventory and Analysis

Note: In 2.1.1.5, the instructions say "close the browser." The user should not close their browser! Please update that to say something like "close the browser tab just created by this report."

2.)

_Replace_

2.1.2: Generate the Application Inventory Report for CustomerOrderServicesApp

_With_

2.1.2: Use the Migration Toolkit for Application Binaries to inventory CustomerOrderServicesApp

_Reason_

Clarity and consistency across headings and to keep the user oriented to the big picture of where they currently are in the 3-Phase migration project.

Note: As before, 2.1.2.5 asks the user to close the entire browser instead of the previously generated tab. Better to say "close the browser tab just created by this report."

3.)

_Replace_

Step 2.2: Analyze the CustomerOrderServicesApp Application code

In this section you will use the WebSphere Application Migration Toolkit (WAMT) to analyze the CustomerOrderServicesApp application code for readiness to run on traditional WebSphere Application ServerV9 (tWAS V9). An Eclipse Workspace has been provided with the CustomerOrderServicesApp Application Source Code already imported. The following features have been installed in to Eclipse IDE for Java EE Developers:

    WebSphere Developer Tools for Eclipse Neon
    WebSphere Application Server Migration Toolkit

_With_

Step 2.2: Use Eclipse IDE Tools to analyze the application code

In this section you will use the WebSphere Application Migration Toolkit (WAMT) to analyze the CustomerOrderServicesApp application code for readiness to run on traditional WebSphere Application ServerV9 (tWAS V9). An Eclipse Workspace has been provided with the CustomerOrderServicesApp Application Source Code already imported.

First, you will need an Eclipse IDE client application on your workstation. 

If you have already installed Eclipse Neon.3, ensure that you have the following plugins installed:

[WebSphere Developer Tools for Eclipse Neon](https://developer.ibm.com/wasdev/downloads/#asset/tools-WebSphere_Developer_Tools_for_Eclipse_Neon)

Note: Select the box for WebSphere Application Server Migration Toolkit as part of the download.

If you have already installed Eclipse Oxygen, ensure that you have the Websphere Developer Tools for Eclipse Oxygen by going to the **Help** menu, selecting **Eclipse Marketplace**, searching for "Websphere Developer Tools", and clicking the **Install** button.

Note: Select the box for WebSphere Application Server Migration Toolkit as part of the download.

If you do NOT have an Eclipse IDE installed on your workstation, or have a version prior to Neon.3, you can download the Eclipse Neon.3 image containing all the necessary tools already installed at the following links. (You may have previously downloaded these in the prerequisites section.)

[Eclipse Neon.3 for Windows w/ WAMT](http://ibm.biz/BdiTNM)
[Eclipse Neon.3 for Mac w/ WAMT](http://ibm.biz/BdiTNv)

Alternatively, you can click here to install Eclipse Neon 3 [Eclipse IDE for Java EE Developers Neon.3](http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/neon3). You will then have to install the Developer Tools and Migration Toolkit plugins as described above.

Second, all users should download the required [Eclipse Workspace - Cross-platform](http://ibm.biz/BdiTNy)  containing the CustomerOrderServicesApp Application Source Code.

_Reason_

The logic flows better and the links are better.

4.) 

_Replace_

2.2.1: Review the CustomerOrderServicesAppApplication Code

In this section you will open a provided Eclipse workspace containing the CustomerOrderServicesApp source code in Eclipse Neon

    You can download the Eclipse image containing all the necessary packages already installed at the following links. (You may have previously downloaded these in the prerequisites section.)

    Eclipse for Windows

    Eclipse for Mac

    Eclipse Workspace - Cross-platform

    Once this is done, open Eclipse with a clean workspace.

Navigate to the Eclipse directory and run Eclipse:

cd {ECLIPSE_NEON_HOME}
eclipse {-clean}

_With_

2.2.1: Analyze the CustomerOrderServicesApp application code

1.) Open Eclipse with a clean workspace, from your application menu or using the command line:

cd {ECLIPSE_NEON_HOME}
eclipse {-clean}

2.) In Eclipse, go to the File menu and choose Import....

3.) Expand General option and select Existing Projects into Workspace.

4.) Choose the option Select Archive File and then browse the workspace refarch-jee-customerorder-was70-dev (Export-Archive-File).zip.

5.) Ensure all four of the CustomerOrderServices projects are selected and click Finish to complete the import.

_Reason_

The logic flows better and the links are better.

The rest of the write up can proceed as it is from there. Once these edits are complete, it should be much easier to follow. I can go through it again for overall flow and to make sure we didn't miss anything.

**Comment by Hemankita** [comment]
Populated the changes in the tutorial as suggested.

**Comment by TyMcCarthy** [comment]
Thanks Hemankita! Actually it looks like you used a previous version of my comment to update the master. Please try refreshing that original issue page to include the edits I made last night. Thanks! LMK if you have any questions. John

**Comment by Hemankita** [comment]
Thank you. Updated the tutorial with the latest rewrite.

**Comment by TyMcCarthy** [comment]
In Section 2.2.1, this line:

cd {ECLIPSE_NEON_HOME} eclipse {-clean}

should be

cd {ECLIPSE_NEON_HOME}
eclipse {-clean}
