### ISSUE TITLE
Additional Strategy Planning Tools

### ISSUE THREAD

**Issue by dhvines** [ibm-cloud-architecture/refarch-jee#3]
Perhaps you want to add these two tools to the strategy planning?
 
1. WAS V9 TCA Calculator (Latest WAS V9 flexible pricing options)
    https://advantage.ibm.com/2015/04/02/was-vs-jboss-license-and-support-cost-calculator-updated/
    Compare your existing S&S costs against the latest WAS V9 flexible license and support options
 
2. WAS V9 TCO Calculator (On-Premise versus In Cloud)
    https://roi-calculator.mybluemix.net/
    Evaluate costs of moving your applications to Bluemix (WAS as a Service, IBM Container, or Buildpack)  

If so, see slides 6-8 in this link from which to start:

https://ibm.box.com/s/luy29aoc7n9vu5g29nbvlh91awz6yzk8

**Comment by Hemankita** [comment]
Added the tools and updated it in the documentation.
